<%@ Page Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="payBills.aspx.cs" Inherits="Patient_payBills" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cph_header" Runat="Server">
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="cph_main" Runat="Server">
    <div>
        <%-- Displys welcome message to user --%> 
    <asp:LoginName ID="log_name" runat="server" FormatString="Welcome, {0} " />

      <%-- Allows user to logout if logged in --%>  
    <asp:LoginStatus ID="log_status" runat="server" LogoutAction="Redirect" LogoutPageUrl="~/index.aspx" />
        <br />

        <!-- Will display to the user what type of account is currently logged in. 
           Because of the web.config file, access to this page is restricted for everyone but an admin; so only the admin role will display -->
    <asp:LoginView ID="log_view" runat="server" >
        <AnonymousTemplate>
            Public User(s)
        </AnonymousTemplate>
        <LoggedInTemplate>
            Logged In User(s)
        </LoggedInTemplate>
        <RoleGroups>
            <asp:RoleGroup Roles="Admin">
                <ContentTemplate>
                    Admin(s) only
                </ContentTemplate>
            </asp:RoleGroup>
            <asp:RoleGroup Roles="User">
                <ContentTemplate>
                    User(s) only
                </ContentTemplate>
            </asp:RoleGroup>
        </RoleGroups>
    </asp:LoginView>


        
        <asp:HyperLink ID="hyp_user_account" runat="server" Text="Account"  NavigateUrl="~/Patient/account.aspx" />


        <br /> <br /> <br />
        <asp:Panel ID="pnl_list" runat="server" >
        <asp:GridView ID="gv_bills_list" runat="server" OnRowCommand="subSelect" AutoGenerateColumns="false" AutoGenerateSelectButton="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" >
            <EmptyDataTemplate>
                <asp:Label ID="lbl_bill_stat" runat="server" Text="You have no invoices" />
            </EmptyDataTemplate>

            <Columns>
                <asp:TemplateField>
                    <HeaderTemplate>
                        <asp:Label ID="lbl_header" runat="server" Text="Invoice List" />
                    </HeaderTemplate>
                    <ItemTemplate>
                                    <asp:Label ID="lbl_invoice_num" runat="server" Text="Invoice Number: " AssociatedControlID="lbl_num" />
                                    <asp:Label ID="lbl_num" runat="server" Text='<%#Eval("Id") %>' />
                                    <asp:LinkButton ID="lnk_select" runat="server" Text="Select" CommandArgument='<%#Eval("Id") %>' CommandName="Selectx" /> 
                                    <br /><br />

                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

        </asp:GridView>
        </asp:Panel>


        <asp:Panel ID="pnl_info" runat="server">
        <asp:DetailsView ID="dv_bills" runat="server" OnItemCommand="subPayform" AutoGenerateRows="false" >
            <Fields>
                <asp:TemplateField>
                    <ItemTemplate>

                                    <asp:Label ID="lbl_invoice_num" runat="server" Text="Invoice #:" AssociatedControlID="lbl_num" />
                                    <asp:Label ID="lbl_num" runat="server" Text='<%#Eval("Id") %>' />
                                    <br /><br />
                                    <asp:Label ID="lbl_colAmount" runat="server" Text="Amount :" AssociatedControlID="lbl_amount" />
                                    <asp:Label ID="lbl_amount" runat="server" Text='<%#Eval("amount") %>' /> 
                                    <br /><br />
                                    <asp:Label ID="lbl_colProcedure" runat="server" Text="Procedure :" AssociatedControlID="lbl_procedure" />
                                    <asp:Label ID="lbl_procedure" runat="server" Text='<%#Eval("procedure") %>' />
                                    <br /><br />
                                    <asp:Label ID="lbl_colStatus" runat="server" Text="Status :" AssociatedControlID="lbl_status" />
                                    <asp:Label ID="lbl_status" runat="server" Text='<%#Eval("status") %>' />
                                    <br /><br />
                        <asp:LinkButton ID="lnk_pay" runat="server" Text="Pay Invoice" CommandArgument='<%#Eval("status") %>' CommandName="Payx" />
                        <br />
                        <asp:LinkButton ID="lnk_print" runat="server" Text="Print Invoice" CommandArgument='<%#Eval("Id") %>' CommandName="Printx" />
                        <br />
                        <asp:LinkButton ID="lnk_cancel" runat="server" Text="Cancel" CommandName="Cancelx" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Fields>
        </asp:DetailsView>
        </asp:Panel>

        <asp:HiddenField ID="hdf_amount" runat="server" Value="" />
        <asp:HiddenField ID="hdf_proc" runat="server" Value="" />
        <asp:HiddenField ID="hdf_id" runat="server" Value="" />
        <asp:HiddenField ID="hdf_pid" runat="server" Value="" />

        <asp:Panel ID="pnl_form" runat="server">

                        <asp:RadioButton ID="rbl_credit" runat="server" Text="Credit Card" OnCheckedChanged="Checked" GroupName="payment" AutoPostBack="true"  />

                        <asp:RadioButton ID="rbl_paypal" runat="server" Text="PayPal" OnCheckedChanged="Checked" GroupName="payment" AutoPostBack="true" />


            <asp:Panel ID="pnl_credit" runat="server">
                <asp:Label ID="lbl_cardnum" runat="server" Text="CardNumber" />
                <asp:TextBox ID="txt_cardNum" runat="server" />
                <asp:RequiredFieldValidator ID="rfv_cardnum" runat="server" ControlToValidate="txt_cardNum" Text="*Required" Display="Static" ErrorMessage="Card number is required" ValidationGroup="payform" />
                <asp:RegularExpressionValidator ID="reg_cardnum" runat="server" ControlToValidate="txt_cardNum" Display="None" ErrorMessage="Invalid Creditcard Number; Enter 16 digits card number, accepts spaces or dash" ValidationExpression="(\d{4}[\-]\d{4}[\-]\d{4}[\-]\d{4})|(\d{16})|(\d{4}[\s]\d{4}[\s]\d{4}[\s]\d{4})" ValidationGroup="payform" />
                <br />
            
                <asp:Label ID="lbl_cardname" runat="server" Text="Card Holder Name" />
                <asp:TextBox ID="txt_cardName" runat="server" />
                <asp:RequiredFieldValidator ID="rfv_cardName" runat="server" ControlToValidate="txt_cardName" Text="*Required" Display="Static" ErrorMessage="Card holder's name is required" ValidationGroup="payform" />
                <asp:RegularExpressionValidator ID="reg_cardName" runat="server" ControlToValidate="txt_cardName" Display="None" ErrorMessage="Invalid Name; characters only" ValidationExpression="[A-Za-z\s]+$" ValidationGroup="payform" />
                <br />
            
                <asp:Label ID="lbl_expire" runat="server" Text="Expire date" />
                <asp:TextBox ID="txt_expireDate" runat="server" />
                <asp:RequiredFieldValidator ID="rfv_date" runat="server" ControlToValidate="txt_expireDate" Text="*Required" Display="Static" ErrorMessage="A expire date is required" ValidationGroup="payform" />
                <asp:RegularExpressionValidator ID="reg_date" runat="server" ControlToValidate="txt_expireDate" Display="None" ValidationExpression="(((0[1-9])|(1[1-2]))\/(\d{4}))" ErrorMessage="Invalid expire date; mm/yyyy " ValidationGroup="payform" />

                <br />
                <asp:Button ID="btn_paybill" runat="server" Text="Pay now" OnClick="subPay" ValidationGroup="payForm" />
                <asp:ValidationSummary ID="vs_payForm" runat="server" HeaderText="Credit Card Form Errors" DisplayMode="BulletList" ShowMessageBox="true" ShowSummary="false" ValidationGroup="payForm" />
                <br />
        </asp:Panel>

        
        
        </asp:Panel>

        <asp:Label ID="test" runat="server" />

    </div>
            
        <asp:Panel ID="pnl_paypal" runat="server">
            <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_xclick"/>
            <input type="hidden" name="business" value="dev-facilitator@j-lacroix.net"/>
            <input type="hidden" name="lc" value="CA"/>
            <input type="hidden" name="item_name" value="<%= hdf_proc.Value %>"/>
            <input type="hidden" name="item_number" value="<%= hdf_id.Value %>"/>
            <input type="hidden" name="amount" value="<%= hdf_amount.Value %>"/>
            <input type="hidden" name="currency_code" value="CAD"/>
            <input type="hidden" name="button_subtype" value="services"/>
            <input type="hidden" name="return" value="http://daniellestirling.com/hospital/processing.aspx" />
            <input type="hidden" name="cancel_return" value="http://daniellestirling.com/hospital/cancel.aspx" />
            <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHosted"/>
            <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"/>
            <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1"/>
            </form>

        </asp:Panel>

    <asp:Label ID="lbl_msg" runat="server" />

</asp:Content>
