<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Master.master"    CodeFile="news.aspx.cs" Inherits="news" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cph_header" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cph_banner" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cph_main" Runat="Server">


    <asp:Label ID="lbl_insert" runat="server"  Text=""/> <%--Insert begins here--%>
    <br />
        <asp:Label ID="lbl_message" runat="server" />
        <br />
         
                <asp:Label ID="lbl_filter" runat="server"   AssociatedControlID="txt_filterI" Text="Publish Before" />
                <asp:TextBox ID="txt_filterI" runat="server" /> 
                <asp:RequiredFieldValidator ID="rvf_filter" runat="server" ControlToValidate="txt_filterI" Text="*Required"  ValidationGroup="insert" />
                <%--user's must enter a value for first name--%> <br />
                <asp:Label ID="lbl_filterafter" runat="server"   AssociatedControlID="txt_filterafterI" Text="Publsh After:" />
                <asp:TextBox ID="txt_filterafterI" runat="server" />
                <asp:RequiredFieldValidator ID="rvf_filterafter" runat="server" ControlToValidate="txt_filterafterI" Text="*Required"  ValidationGroup="insert" /> <%--user's must enter a value for last name--%><br />
                <asp:Label ID="lbl_date" runat="server"   AssociatedControlID="txt_dateI" Text="Date:" />
                <asp:TextBox ID="txt_dateI" runat="server" />
                <asp:RequiredFieldValidator ID="rvf_date" runat="server" ControlToValidate="txt_dateI" Text="*Required"  ValidationGroup="insert" /> <%--user's must enter a value for last name--%><br />
                <br />
                <asp:Panel ID="pnl_cbl" runat="server">
                <asp:CheckBoxList id="cbl_dep"  runat="server" AutoPostBack="true"    OnSelectedIndexChanged="CheckBoxList_SelectedIndexChanged">
                <asp:ListItem>Administration</asp:ListItem>
                <asp:ListItem>Patient Care</asp:ListItem>
                <asp:ListItem>Community Programs</asp:ListItem>
                <asp:ListItem>Operational Services</asp:ListItem>
                <asp:ListItem>Partnerships</asp:ListItem>
                </asp:CheckBoxList>
                <asp:ListView ID="lst_details" runat="server" OnRowCommand="subSelect" AutoGenerateColumns="false" AutoGenerateSelectButton="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" OnItemCommand="ListView1_ItemCommand">
                <ItemTemplate>
                    <table>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            
                        </tr>
                        <tr>
                            <td>
                                <asp:Label ID="LabelId"  runat="server" Text='<%#Eval("id") %>'></asp:Label></td>
                            <td> <asp:TextBox ID="TextBoxName" runat="server" Text='<%#Eval("Department") %>'></asp:TextBox></td>
                      </tr>
                        <td>
                        <asp:LinkButton ID="lnk_select" runat="server" Text="Select" CommandArgument='<%#Eval("Id") %>' CommandName="Selectx" /> 
                        </td>
                    </table>
                </ItemTemplate>
               
            </asp:ListView>
                 </asp:Panel>
                <br />
                 
              <%--  <asp:Button ID="btn_cancel" runat="server" Text="Cancel" OnCommand="subAdmin" CommandName="Cancel"  />--%>
                <asp:ValidationSummary ID="vds_main" runat="server" HeaderText="Errors:" ShowMessageBox="true" ShowSummary="false" />
                <hr />
        <p>
 
</p>  
        <%--extended login control authenticates, creates and change users, redirects user to another page using a url--%>
   </asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cph_IB" Runat="Server">
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="cph_donate" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="cph_cal" Runat="Server">
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="cph_map" Runat="Server">
</asp:Content>
<asp:Content ID="Content9" ContentPlaceHolderID="cph_other" Runat="Server">
</asp:Content>
