<?xml version="1.0" encoding="utf-8"?><Database Name="DB_66299_aspproject" Class="dropDownFillDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DeetaBase.db.12042275.hostedresource.com;User ID=DeetaBase" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCountry" Member="tblCountries">
    <Type Name="tblCountry">
      <Column Name="countryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="countryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="tblCountry_tblProvince" Member="tblProvinces" ThisKey="countryId" OtherKey="provinceCountryId" Type="tblProvince" />
    </Type>
  </Table>
  <Table Name="dbo.tblProvince" Member="tblProvinces">
    <Type Name="tblProvince">
      <Column Name="provinceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="provikceName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="provinceCountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblProvince_tblCity" Member="tblCities" ThisKey="provinceId" OtherKey="cityProvinceId" Type="tblCity" />
      <Association Name="tblCountry_tblProvince" Member="tblCountry" ThisKey="provinceCountryId" OtherKey="countryId" Type="tblCountry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCity" Member="tblCities">
    <Type Name="tblCity">
      <Column Name="cityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cityName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cityProvinceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblProvince_tblCity" Member="tblProvince" ThisKey="cityProvinceId" OtherKey="provinceId" Type="tblProvince" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.donorInformation" Member="donorInformations">
    <Type Name="donorInformation" Id="ID1">
      <Column Name="donorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="donorAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="donorTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="donorFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="donorMiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donorLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonorType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonorCompany" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donorZipCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="donorPoBox" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donorCountry" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="donorProvince" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="donorCity" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="donorEmail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="donorPhoneHome" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="donorPhoneWork" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="donorEmailSend" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblRoomType" Member="tblRoomTypes">
    <Type Name="tblRoomType">
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="roomType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="roomTotleBed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblRoomType_tblBedRoom" Member="tblBedRooms" ThisKey="roomId" OtherKey="bedRoomId" Type="tblBedRoom" />
    </Type>
  </Table>
  <Table Name="dbo.tblBedRooms" Member="tblBedRooms">
    <Type Name="tblBedRoom" Id="ID2">
      <Column Name="bedId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bedAvailable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bedRoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblRoomType_tblBedRoom" Member="tblRoomType" ThisKey="bedRoomId" OtherKey="roomId" Type="tblRoomType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTickets" Member="tblTickets">
    <Type Name="tblTicket">
      <Column Name="ticketId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ticketNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spGetDonorInformation" Method="spGetDonorInformation">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spGetDonorInformationById" Method="spGetDonorInformationById">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spUpdateDonorInformation" Method="spUpdateDonorInformation">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="amount" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="firstname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="middle" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="company" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="zipcode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pobox" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="country" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="province" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="city" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="phonehome" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="phonework" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="emailsend" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertDonorInformation" Method="spInsertDonorInformation">
    <Parameter Name="amount" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="firstname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="middle" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="company" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="zipcode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pobox" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="country" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="province" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="city" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="phonehome" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="phonework" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="emailsend" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateBedRooms" Method="spUpdateBedRooms">
    <Parameter Name="bedcount" Type="System.Int32" DbType="Int" />
    <Parameter Name="bedid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetBedRoomAndRoomType" Method="spGetBedRoomAndRoomType">
    <ElementType IdRef="ID2" />
  </Function>
</Database>